name: Documentation

on:
  push:
    branches: [main]
    tags: '*'
  pull_request:
  
  
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build:
    permissions:
      contents: write
      pages: write
      id-token: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node & External Dependencies # This is still useful because it caches the node_modules so we don't constantly re-install.  You don't technically need this, though.
        uses: actions/setup-node@v4
        with:
            node-version: 20
            cache: npm 
            cache-dependency-path: 'docs/package-lock.json' # this should be a package-lock.json file
      - run: sudo apt-get update && sudo apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
      - run: cd docs/; rm package-lock.json; npm install; cd ..
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'
      - name: Pull Julia cache
        uses: julia-actions/cache@v1
      - name: Install docs dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.develop([PackageSpec(path=pwd()), PackageSpec(path="https://github.com/LuxDL/DocumenterVitepress.jl.git")]); Pkg.instantiate()'
      - name: Install examples dependencies
        run: julia --project=examples -e 'using Pkg; Pkg.develop([PackageSpec(path=pwd()),]); Pkg.instantiate()'
      - name: Install custom documentation dependencies
        run: DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia --project=docs -e 'using Pkg; pkg"dev ."; Pkg.instantiate(); Pkg.precompile(); Pkg.status()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
          GKSwstype: "100"
          JULIA_DEBUG: "Documenter"
          DATADEPS_ALWAYS_ACCEPT: true
        run: |
          DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia --project=docs/ --color=yes docs/make.jl